image:
  file: .gitpod.Dockerfile
tasks:
 - name: Setup wokwi alias
   command: |
      alias wokwi='bash /workspace/ferrous-training/wokwi/run.sh'
vscode:
  extensions:
    - matklad.rust-analyzer
    - tamasfe.even-better-toml
    - vadimcn.vscode-lldb
    - anwar.resourcemonitor
    - yzhang.markdown-all-in-one
    - serayuzgur.crates
ports:
  - port: 9012
    visibility: public